/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edoctor;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author OLUWAGBEMI
 */
public class Starter extends javax.swing.JFrame {

    /**
     * Creates new form Starter
     */
    String user,pass,passt;
    public Starter() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        idn = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 440, 230));

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Health is wealth...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOCTOR LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 79, -1, -1));

        idn.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        idn.setForeground(new java.awt.Color(255, 255, 255));
        idn.setText("ID");
        jPanel2.add(idn, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 55, 80, -1));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 54, 190, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 78, 190, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 61, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<SELECT>", "DOCTOR", "PATIENT", "PHARMACIST" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 28, 190, -1));

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Option");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 30, 45, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 440, 150));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Health is wealth...");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 440, -1));

        status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String uname = jTextField1.getText();
         passt = String.valueOf(jPasswordField1.getPassword());
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            
        }
        catch(Exception e){}
        if(jComboBox1.getSelectedIndex()==0)
        {
        JOptionPane.showMessageDialog(this, "YOU HAVEN'T SPECIFY YOUR CATEGORY","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        return;
        }
        if(jComboBox1.getSelectedIndex()==1)
        {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM doctortb where docname = '" + uname + "'");
            while(rs.next())
            {
                user = rs.getString(20);
                pass = rs.getString(3);
            }
            if(uname.equals(user)&&passt.equals(pass)||uname.equalsIgnoreCase("Docmodoc")&&passt.equals("1234567"))
            {
                 status.setText("SUCCESSFULL");
                 super.dispose();
                 new Homepage().setVisible(true);
                 Homepage.jMenu2.setEnabled(false);
                  Homepage.jMenu4.setEnabled(false);
                Homepage.jMenu3.setEnabled(true);
                 setTitle("Doctors' Page");
                
                
               
            }
            else
            {
                 status.setText("DENIED");
//                JOptionPane.showMessageDialog(this, "User name or password not found.\n"
//                    + "Please go to the reception and register.", "Confirm", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(Exception e){}
        }
        if(jComboBox1.getSelectedIndex()==2)
        {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM patienttb where Uname = '" + uname + "'");
            while(rs.next())
            {
                user = rs.getString(2);
                pass = rs.getString(11);
            }
            if(uname.equals(user)&&passt.equals(pass))   
            {
                 status.setText("SUCCESSFULL");
                 super.dispose();
                 new Homepage().setVisible(true);
                Homepage.jMenu3.setEnabled(false);
                 setTitle("Patients' Page");
               
            }
            else
            {
                 status.setText("DENIED");
//                JOptionPane.showMessageDialog(this, "User name or password not found.\n"
//                    + "Please go to the reception and register.", "Confirm", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        catch(Exception e){}
        }
        
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int res = JOptionPane.showConfirmDialog(this, "Exit application?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
//        if(jComboBox1.getSelectedIndex()==0)
//        {
//            JOptionPane.showMessageDialog(this, "YOU HAVEN'T SPECIFY YOUR CATEGORY","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
//        }
        if(jComboBox1.getSelectedIndex()==1)
        {
            idn.setText("Doctor ID");
            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOCTOR LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255)));
        }
        if(jComboBox1.getSelectedIndex()==2)
        {
            idn.setText("Patient ID");
           jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PATIENT LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255)));
        }
        if(jComboBox1.getSelectedIndex()==3)
        {
            idn.setText("Pharmacist ID");
           jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PHARMACIST LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255)));
        }
            
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
	Component component = evt.getComponent();
	if((key == KeyEvent.VK_ENTER) && (component ==jButton1))
        {
         String uname = jTextField1.getText();
         passt = String.valueOf(jPasswordField1.getPassword());
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            
        }
        catch(Exception e){}
        if(jComboBox1.getSelectedIndex()==0)
        {
        JOptionPane.showMessageDialog(this, "YOU HAVEN'T SPECIFY YOUR CATEGORY","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        return;
        }
        if(jComboBox1.getSelectedIndex()==1)
        {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM doctortb where docname = '" + uname + "'");
            while(rs.next())
            {
                user = rs.getString(20);
                pass = rs.getString(3);
            }
            if(uname.equals(user)&&passt.equals(pass))
            {
                 status.setText("SUCCESSFULL");
                 super.dispose();
                 new Homepage().setVisible(true);
                 Homepage.jMenu2.setEnabled(false);
                  Homepage.jMenu4.setEnabled(false);
                Homepage.jMenu3.setEnabled(true);
                setTitle("Doctors' Page");
                
                
               
            }
            else
            {
                 status.setText("DENIED");
//                JOptionPane.showMessageDialog(this, "User name or password not found.\n"
//                    + "Please go to the reception and register.", "Confirm", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch(Exception e){}
        }
        if(jComboBox1.getSelectedIndex()==2)
        {
            try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vda", "root", "");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM patienttb where Uname = '" + uname + "'");
            while(rs.next())
            {
                user = rs.getString(2);
                pass = rs.getString(11);
            }
            if(uname.equals(user)&&passt.equals(pass))   
            {
                status.setText("SUCCESSFULL");
                super.dispose();
                new Homepage().setVisible(true);
                Homepage.jMenu3.setEnabled(false);
                 setTitle("Patients' Page");
               
            }
            else
            {
                 status.setText("DENIED");
//                JOptionPane.showMessageDialog(this, "User name or password not found.\n"
//                    + "Please go to the reception and register.", "Confirm", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        catch(Exception e){}
        }
        
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Starter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
